[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
now_settlement = "7nqsPpBhpUwSahMrpuAPNMupx2vVEGqkU6XXcng7VaAm"

[programs.devnet]
now_settlement = "7nqsPpBhpUwSahMrpuAPNMupx2vVEGqkU6XXcng7VaAm"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
