[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
now_settlement = "6HnAnrNjHWzyJ6RSDZtQ9mPWGwYehSmw1H8T2RKBwWwA"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
